version: "2"
run:
  modules-download-mode: vendor
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - lll
    - mnd
    - nlreturn
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - vendor$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - vendor$
